### PR TITLE
minimal Q3C translator

### PR DESCRIPTION
**Pull request by tsdower**
Supports Q3C spatial indexed queries for Postgres-backed ADQL queries.
Q3C: https://github.com/segasai/q3c

This is a minimal implementation of point-in-circle, or cone search, queries in TAP. Many of MAST's TAP catalogs only provide this level of spatial query support, we can improve on this if a catalog needs it. The class is mostly templated from pre-existing pgSphere support. It has no effect on MSSQL-backed catalog support.

I've tentatively marked the version 1.5-4, as we still do not have full ADQL 2.1 in here.

### CODE REVIEW

**Comment by jwfraustro** [comment]
This looks fine to me, from what I can see. I think keeping it at 1.5-4 is fine, until we've got time to revisit the 2.1 branch I made. Which is still waiting on a bug fix from Grégory, I think.

**Review by jwfraustro — APPROVED** [review]

**Comment by chamblee-st** [comment]
Does this work with vo-tap or ADQL-translator? If so, how?

**Comment by jwfraustro** [comment]
> Does this work with vo-tap or ADQL-translator? If so, how?

This a fork of Grégory Mantele's [vollt library](https://github.com/gmantele/vollt) which, among other things, implements a parser for the ADQL syntax that can convert it into various SQL dialects. We use a fork of it with our own translator to handle some MAST SQL-Server specific geometry function quirks I can't remember off the top of my head.

**Comment by tsdower** [comment]
> Does this work with vo-tap or ADQL-translator? If so, how?

What @jwfraustro said!
The ADQL-translator is a wrapper around the 'adql' portion of this forked library. Another IVOA contributor maintains the main project with the intention of supporting TAP's query language to multiple database back ends. We contribute to portions supporting databases MAST uses, keeping our changes in a fork where they are very MAST specific or initiating pull requests where they are more generic.

We should probably talk with Gregory about whether Q3C support would be welcome upstream, as it is not particularly MAST specific. (We may want to make it more robust and generic before offering code though.)

**Pull request merged**
